In [1]:
#Initialize Django
import os

#Import utility libraries
from datetime import datetime, timedelta

#Import pyodbc
import pyodbc

#Import pandas
import pandas as pd

#Import project libraries
os.chdir('c:/') #path where availability_data is saved
from availability_data import Availability

In [2]:
department = 'pasting'
start_date = '2020-09-13'
end_date = '2020-09-14'
dt_format = '%Y-%m-%d'
quality_loss = 0

days = (datetime.strptime(end_date, dt_format) - datetime.strptime(start_date, dt_format)).days
availability = Availability(end_date, department, days=days, quality_loss=quality_loss)

In [3]:
#Shows data for jobs
availability.job_table.head()

,start_time,end_time,deviceKey,part_id,good_count,total_count,takt_time
0,2020-09-13 23:24:41,2020-09-14 06:47:05,SalPastingL02,9EM0770HN,109452.0,109452.0,0.100446
1,2020-09-13 20:00:05,2020-09-15 10:32:21,SalPastingL05,2ZW0620UP,961454.0,961454.0,0.100446
2,2020-09-13 18:21:48,2020-09-14 06:12:47,SalPastingL01,9EW0630HN,204660.0,102330.0,0.100446
3,2020-09-13 18:13:25,2020-09-13 23:24:41,SalPastingL02,9EM0720HN,97792.0,97792.0,0.100446
4,2020-09-13 16:51:51,2020-09-14 21:46:18,SalPastingL04,0ZM0850UP,332684.0,332685.0,0.100446

In [4]:
#Shows data for shifts
availability.shift_table.head()

           start_time      deviceKey  good_count  total_count  takt_time
0 2020-09-13 18:05:02  SalPastingL05    311728.0     311728.0   0.100446
1 2020-09-13 18:05:01  SalPastingL06    159616.0     159616.0   0.100446
2 2020-09-13 18:05:01  SalPastingL03    172934.0     172934.0   0.100446
3 2020-09-13 18:05:01  SalPastingL02    203814.0     203814.0   0.100446
4 2020-09-13 18:05:01  SalPastingL01    207060.0     103530.0   0.100446

In [5]:
#Shows all events
availability.data.head()

               start_time      deviceKey state_text  reason_text  duration
0 2020-09-14 05:32:17.340  SalPastingL01   run_enum      Running  0.241825
1 2020-09-14 05:31:45.630  SalPastingL02   run_enum      Running  0.260714
2 2020-09-14 05:31:30.710  SalPastingL06   run_enum      Running  0.084411
3 2020-09-14 05:31:08.630  SalPastingL03  down_enum         None  0.101889
4 2020-09-14 05:28:47.060  SalPastingL01  down_enum  Hopper Jams  0.058397